### ISSUE TITLE
"Toggle Search Details" button is invisible

### ISSUE THREAD

**Issue by markovaljaots** [slack-theme/visual-studio-code#5]
This button is invisible In the sidebar when using the Light theme.

![invisible_btn](https://user-images.githubusercontent.com/14821242/47205936-0f491800-d390-11e8-8c5e-9c9a66299cbf.png)

**Comment by felipemendes** [comment]
Thanks for your feedback, @markovaljaots . This issue is due the dark background color in a light theme. On light theme in VS Code the icons use this default dark gray color. I haven't figure it out how to change it, thats why I made the dark theme in the begging to try to solve this problem. But without success. Anyway, I will try to fix this :)

**Comment by felipemendes** [comment]
Fix button colors on version [v.1.7.3](https://github.com/slack-theme/visual-studio-code/blob/master/CHANGELOG.md#changed)
![screen shot 2018-10-30 at 20 37 43](https://user-images.githubusercontent.com/3712089/47757119-b2990780-dc83-11e8-8a44-2f52d9f18229.png)
